name: Run Unit Tests

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20 

    - name: Navigate to project directory
      run: cd multi-service-models

    - name: Install dependencies
      run: npm install
      working-directory: ./multi-service-models

    - name: Run tests
      run: npm test
      working-directory: ./multi-service-models